package py.pol.una.sd;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;

public class ClientGUI extends JFrame {
    private JPanel contentPanel;
    private JTextPane chatPane;
    private JScrollPane scrollPane;

    public ClientGUI() {
        setTitle("Chatroom");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(contentPanel);
        pack();

        setLocationRelativeTo(null);

        setVisible(true);
    }

    private void setupChatPane() {
        StyledDocument doc = chatPane.getStyledDocument();

        // configurar estilos para usuario y mensaje
        Style userStyle = chatPane.addStyle("UserStyle", null);
        StyleConstants.setForeground(userStyle, Color.BLUE);
        StyleConstants.setBold(userStyle, true);

        Style messageStyle = chatPane.addStyle("MessageStyle", null);
        StyleConstants.setForeground(messageStyle, Color.BLACK);
    }

    public void addMessage(String user, String message) {
        StyledDocument doc = chatPane.getStyledDocument();

        try {
            doc.insertString(doc.getLength(), user + ": ", chatPane.getStyle("UserStyle"));
            doc.insertString(doc.getLength(), message + '\n', chatPane.getStyle("MessageStyle"));

            chatPane.setCaretPosition(doc.getLength());

        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane = new JScrollPane();
        contentPanel.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        chatPane = new JTextPane();
        scrollPane.setViewportView(chatPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
